"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.errorOnConflict = exports.useExistingFolder = exports.renameOnConflicts = exports.askOnConflicts = exports.upsertOnConflicts = exports.replaceOnConflicts = exports.skipOnConflicts = void 0;
exports.skipOnConflicts = 'skip';
exports.replaceOnConflicts = 'replace';
exports.upsertOnConflicts = 'upsert';
exports.askOnConflicts = 'ask';
exports.renameOnConflicts = 'rename';
exports.useExistingFolder = 'useFolder';
exports.errorOnConflict = 'error';
